### ISSUE TITLE
Create a git-annex repo for data from NYU

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/ms-lesion-agnostic#15]
The data is stored in `duke/mri/nyu/2017-sheperd`.
The steps are the following:
- [x] A git-annex repo should be created : 
- [x] The data should be Bidsfied
- [x] The data should be pushed to the repo
- [x] A PR should be opened
- [x] The PR should be merged. 

@jcohenadad What name should be used for the git-annex repo ? nyu-ms-shepherd ? 

@mguaypaq Could you create the corresponding git-annex repo ?

**Comment by plbenveniste** [comment]
I created the folder `~/duke/temp/plben/create_nyu_gitannex` to work on this:
The data contains:
```console
├── List for JCA.xlsx
└── Spine diffusion data anonymized
    ├── Icon\015
    ├── NYU-100_AXT2_s6.nii
    ├── NYU-100_SAGT2_s3.nii
    ├── NYU-101_AXIT2_s6.nii
    ├── NYU-101_SAGT2_s3.nii
    ├── NYU-102_AXT2LOWER_s11.nii
    ├── NYU-102_AXT2UPPER_s9.nii
    ├── NYU-102_PosDisp11AXT2LOWER_s5002.nii
    ├── NYU-102_PosDisp9AXT2UPPER_s5001.nii
    ├── NYU-102_SAGT2COMPOSED_s5003.nii
    ├── NYU-102_SAGT2LOWER_s6.nii
    ├── NYU-102_SAGT2UPPER_s3.nii
     ...
```
From my first observation of the data, I can see the following: 
- the files are stored as Niftis: this is going to be a problem to create the JSON sidecars: How should I proceed ? 
- there is an `Icon 015` file : what is it ? 
- the list contains the following information : 
   - NYU CODE
   - SCAN DATE
   - MAGNET
   - AGE
   - GENDER
   - MS TYPE 
   - DURATION
   - PDSS
   - PDDS Date

**Comment by jcohenadad** [comment]
> the files are stored as Niftis: this is going to be a problem to create the JSON sidecars: How should I proceed ?

We've done this in the past. Maybe @NathanMolinier @valosekj or @Nilser3 have some scripts to generate missing JSON (if so we should put it under ivadomed/utils)

> there is an Icon 015 file : what is it ?

no idea-- what's in there?

> the list contains the following information

relevant info-- some of it could go under `participants.tsv` (as new columns). Or we use another TSV file for clinical data (@valosekj and @sandrinebedard recently dealt with this question)

**Comment by valosekj** [comment]
> We've done this in the past. Maybe @NathanMolinier @valosekj or @Nilser3 have some scripts to generate missing JSON (if so we should put it under ivadomed/utils)

In the past, when I had no access to dicom headers or any details about the sequences, I simply created empty JSON sidecars. But, IIRC, @mguaypaq then deleted these empty JSON sidecars because they raised errors when the bids-validator was run. (and they were also bringing no information)

> relevant info-- some of it could go under participants.tsv (as new columns). Or we use another TSV file for clinical data (@valosekj and @sandrinebedard recently dealt with this question)

In this case, when you have relatively few columns, I would include everything directly into `participants.tsv` (as done, for example, for `canproco`). Just FYI, if you had more clinical data (tens of columns), you could put this info under `phenotype` (see `dcm-zurich` for an example).

**Comment by plbenveniste** [comment]
I found that some of the data was already in `sct-testing-large` (files named sub-nyuSheperd...). 
However, there are still a number of problems:
- not every image was added to `sct-testing-large`: for instance, the image which have large fields of view (images merging both upper and lower spinal cord) were not added
- also, the data regarding the patients were not added (age, phenotype, scores...)

Therefore, I would recommend going forward with the creation of this dataset which would contain all the information in one place and removing the subjects from `sct-testing-large`. I feel that smaller well organized datasets makes more sense than a big dataset containing various pathologies and data sources.
What is your opinion @jcohenadad ?

**Comment by jcohenadad** [comment]
> Therefore, I would recommend going forward with the creation of this dataset which would contain all the information in one place and removing the subjects from sct-testing-large. I feel that smaller well organized datasets makes more sense than a big dataset containing various pathologies and data sources. It would also avoid this from happening (thinking that the data is not bidsified).

agreed 100%

**Comment by plbenveniste** [comment]
The following code was ran : 

```console
mkdir code
mkdir derivatives
touch dataset_description.json
touch participants.json
touch participants.tsv
touch README.md
cd ..

python bids-ms-nyu/code/convert2bids.py --d ./2017-shepherd/Spine\ diffusion\ data\ anonymized/ --o ./bids-ms-nyu/ --p ./2017-shepherd/List\ for\ JCA.xlsx 

```


The dataset was created and is stored on duke for now (waiting for a git-annex repo to be created).
I decided not to add any image containing 'POS' as they are 2D images (or only 2 or 3 slices). 
When the COMP file was present (multiple images fused together), the files used for building it were not added. 
 
The following files had multiple acquisition, only the last one was kept (the ones below): 
- NYU-54_AXT2_S9.NII
- NYU-83_SAGT2UPPER_S6.NII
- NYU-115_AXIT2LOWER_S25.NII
- NYU-115_AXIT2UPPER_S21.NII
- NYU-41_AXIT2LOWER_S12.NII
- NYU-41_SAGT2LOWER_S22.NII 
- NYU-41_SAGT2UPPER_S8.NII 
- NYU-113_AXT2_S5.NII 
- NYU-113_SAGT2_S5.NII
- NYU-31_AXT2_S11.NII
- NYU-12_SAGT2_S6.NII 
- NYU-71_AXT2_S7.NII

The following files were not added eventhough they weren't used for building a COMP file (for simplicity purposes):
- NYU-95_SAGT2UPPERCOUNTER_S2.NII
- NYU-138_SAGT2COUNTER_S100.NII
- NYU-165_SAGT2LOWERCOUNTER_S4.NII
- NYU-165_SAGT2UPPERCOUNTER_S2.NII
- NYU-125_SAGT2LOWERCOUNTER_S7.NII
- NYU-125_SAGT2UPPERCOUNTER_S6.NII
- NYU-116_SAGT2LOWERCOUNTER_S12.NII
- NYU-116_SAGT2UPPERCOUNTER_S11.NII
- NYU-56_SAGT2LOWERCOUNTER_S5.NII
- NYU-56_SAGT2UPPERCOUNTER_S4.NII
- NYU-156_SAGT2UPPERCOUNTER_S3.NII
- NYU-63_SAGT2LOWERCOUNTER_S4.NII
- NYU-63_SAGT2UPPERCOUNTER_S2.NII
- NYU-107_SAGT2LOWERCOUNTER_S2.NII
- NYU-122_SAGT2LOWERCOUNTER_S5.NII
- NYU-122_SAGT2UPPERCOUNTER_S3.NII'

Now moving on to transferring the segmentations from sct-testing-large to this dataset.

**Comment by plbenveniste** [comment]
The segmentations were transferred using the script in `code/transferring_segmentations.py`. 

All the segmentation stored were matched with a corresponding image (by comparing data in each image from `sct-testing-large` and from `ms-nyu`). 

Waiting for the git-annex repo to be created to push everything.

**Comment by plbenveniste** [comment]
Some modifications need to be done : 

- [ ] The files which have multiple acquisitions should be kept for the interest of having some artifacted images (for  @simonqueric's project)

**Comment by plbenveniste** [comment]
The files were added in the BIDS folder. When there are two files, they follow the following name convention: 
- sub-071_acq-ax_T2w.nii.gz
- sub-071_acq-ax_run-02_T2w.nii.gz

Supposedly (from my observations), the first file is artifacted and the second file (file run-02) is the better version.

**Comment by mguaypaq** [comment]
I created the repo and gave @plbenveniste write access:
https://data.neuro.polymtl.ca/datasets/ms-nyu

**Comment by plbenveniste** [comment]
Data was pushed to branch plb/first_data_push_nyu and PR was opened. Ready for review.

**Comment by plbenveniste** [comment]
PR reviewed and merged by @mguaypaq ! Thanks for the review 😃
