### ISSUE TITLE
Question for NYU Shepherd regarding `ms-nyu` metadata

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/ms-lesion-agnostic#18]
Opening this issue to answer a question regarding the data sent by NYU Shepherd from 2017. 
The file `List for JCA.xlsx` contains data describing the participants. 
However, some things are unclear: 
- What does `duration` refer to ? (Duration of disease maybe ?) What is the unit of the duration (months maybe ?)
- What is `PDDS date` ? Is it the date of the Patient Determined Disease Steps ? If so, is it the date when the PDSS score was established ? Or is it just a typo and supposed to be PDSS date ?

Linked to #15 

Tagging @jcohenadad

**Comment by plbenveniste** [comment]
@jcohenadad Could we move forward with this? I don't think any other question should come up regarding this dataset.

**Comment by jcohenadad** [comment]
yup! I'll email him now

**Comment by plbenveniste** [comment]
Here is the response from Timothy Shepherd:

> Duration should be in years since presentation/diagnosis.
> PDSS date is day it was characterized or measured – it is surrogate for EDSS.
