### ISSUE TITLE
Create a git-annex repo for data from `basel/6900_nifti_20`

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/ms-lesion-agnostic#20]
The data is stored in `duke/mri/basel/6900_nifti_20` and the segmentations in `duke/mri/basel/6900_20_lesions-PD`
The steps are the following:

- [x]  A git-annex repo should be created :
- [x]  The data should be Bidsfied
- [x]  The data should be pushed to the repo
- [x]  A PR should be opened
- [x]  The PR should be merged.

@jcohenadad What name should be used for the git-annex repo ? `ms-basel-pd-6900` ?

Another strategy could be to merge this data with the other dataset under construction from basel  (issue #19)

**Comment by plbenveniste** [comment]
In this case, the data is stored in  `duke/mri/basel/6900_nifti_20`. The files are already .nii.gz files. Unfortunately, the folder doesn't contain the images' json sidecar. The data spans from 2017 until 2020. Therefore we chose to use the git annex repo name `ms-basel-2020` (discussed [here](https://github.com/ivadomed/ms-lesion-agnostic/issues/19#issuecomment-2211954551)). Each subject contains multiple acquisitions for two chunks (cervical = chunk I ; thoracic = chunk II). 

As for the segmentation, the segmentations also don't have the a json sidecar. They were done for both thoratic and cervical chunks but only for sag pd images. 

@jcohenadad Should I consider that the contacts for this data is the same as the one for `ms-basel-2020` ? (You should note that this time, the number is 6900) And, was it again Haris Tsagkas who segmented the the lesions ? 

@mguaypaq Could you create the git-annex repo `ms-basel-2020` for this dataset?

**Comment by jcohenadad** [comment]
> @jcohenadad Should I consider that the contacts for this data is the same as the one for ms-basel-2020 ? (You should note that this time, the number is 6900) And, was it again Haris Tsagkas who segmented the the lesions ?

yes and yes. Please also refer to this discussion in the README.

**Comment by plbenveniste** [comment]
The script `bidsification.py` was wrote to do the following: 
- create the necessary files and folders to have the data in the BIDS format.
- deal with the segmentation files and create the json sidecar files.
- create the participants.tsv and participants.json files.
- create the dataset_description.json file.
- fix the header of the segmentation files that are not in the same orientation as the image files.
- convert the files to uint8 if they are not already.

The `README.md` was completed. 

Ready to be pushed when repo is created.

**Comment by plbenveniste** [comment]
Code was updated to use `sct_register_multimodal` similarly to what was done in #19  and to update the json sidecars. 

The code was run using: 
```console
python ms-basel-2020/code/bidsification.py --i 6900_nifti_20/ --o ms-basel-2020/ --s 6900_20_lesions-PD/
```

**Comment by mguaypaq** [comment]
The repo is created, and @plbenveniste has write access:
https://data.neuro.polymtl.ca/datasets/ms-basel-2020

**Comment by plbenveniste** [comment]
PR was opened and it is ready for review !

**Comment by plbenveniste** [comment]
The naming conventions were reviewed (by me) and everything looked fine ! 
PR is ready for review

**Comment by plbenveniste** [comment]
The PR was merged ! Thanks @mguaypaq 😃
