### ISSUE TITLE
Creation of the MP2RAGE dataset from Rennes

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/ms-lesion-agnostic#33]
Opening this issue to create a Git-Annex repository containing the MP2RAGE data from Rennes. 

I received the access today. The data can be accessed using Shanoir. 

What name should be used ? `ms-rennes-mp2rage`?

Tagging @jcohenadad to confirm the name of the gitannex dataset 

Tagging @mguaypaq to create the gitannex repo after confirmation from Julien.

**Comment by mguaypaq** [comment]
The repo is created, and @plbenveniste has write access:
https://data.neuro.polymtl.ca/datasets/ms-rennes-mp2rage

**Comment by plbenveniste** [comment]
Thanks @jcohenadad and @mguaypaq. 

I opened a PR in the git-annex dataset. The data was pushed as a zip file in the sourcedata folder. 

TODO: 

- [ ] Bidsification of the dataset to our standards

**Comment by plbenveniste** [comment]
Changes done ! Ready for review now !

**Comment by plbenveniste** [comment]
PR was reviewed and merged ! Thanks @mguaypaq ! 😃 

Tagging @Nilser3 who wanted to use the data !
