### ISSUE TITLE
Organization of the project with Mayo clinic

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/ms-lesion-agnostic#38]
In the context of the project with Mayo clinic for the detection of "critical" MS lesions, we received some data today.  The data is in the DICOM format. Following up on this, I have a few questions: 

- Should we create a specific GitHub repository for this project ? Otherwise, we can integrate it into this existing repo.  
- The data received today is not the official data for this project (just a sample): should we git-annex it ? If so, what dataset name ? 

Tagging @jcohenadad for input

**Comment by jcohenadad** [comment]
> Should we create a specific GitHub repository for this project ? Otherwise, we can integrate it into this existing repo.

Yes, I think we should. I suggest under [sct-pipeline](https://github.com/sct-pipeline) organization, given that we will be mostly developing a pipeline. Here you go: https://github.com/sct-pipeline/critical-ms-lesion
